rabbitmq.use.ssl=true
rabbitmq_connector.host=localhost
rabbitmq_connector.port=5671
rabbitmq_connector.username=obp
rabbitmq_connector.password=obp
rabbitmq_connector.virtual_host=/

rabbitmq.adapter.enabled=false 
keystore.path=obp-api/src/test/resources/cert/server.jks
keystore.password=123456
truststore.path=obp-api/src/test/resources/cert/server.trust.jks


suggested_default_sca_method=DUMMY
consumer_validation_method_for_consent=CONSUMER_KEY_VALUE
consents.allowed=true
create_system_views_at_boot=true
additional_system_views=ReadAccountsBerlinGroup,ReadBalancesBerlinGroup,ReadTransactionsBerlinGroup,InitiatePaymentsBerlinGroup
allow_account_firehose=true
# control access to customer firehose.
allow_customer_firehose=true

migration_scripts.enabled=true
migration_scripts.execute_all=true

allow_public_views =true
display_internal_errors = true
#allow_firehose_views=false

#outbound.optional.fields=InBoundCreateTransactionRequestv210.data.future_date,InBoundCreateTransactionRequestv210.data.payment_start_date,
#inbound.optional.fields=InBoundCreateTransactionRequestv210.data.future_date,InBoundCreateTransactionRequestv210.data.payment_start_date,

#connector=rabbitmq_vOct2024
connector=star
starConnector_supported_types = mapped,rabbitmq_vOct2024,cardano_vJun2025,ethereum_vSept2025,internal,stored_procedure_vDec2019
#grpc_vFeb2024

#implicitly_convert_ids=true
connector.name.export.as.endpoints=mapped
BG_remove_sign_of_amounts=true
akka_connector.hostname=127.0.0.1
akka_connector.port=2662

#obp-mapped (9.5-BigSql:5436)
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/obp-mapped?user=postgres&password=f


#db.driver=org.h2.Driver
#db.url=jdbc:h2:./h2_new.db;NON_KEYWORDS=VALUE;DB_CLOSE_ON_EXIT=FALSE

#db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
#db.url=jdbc:sqlserver://10.0.4.24:1433;databaseName=hongwei;user=admin;password=5p4b2fEkVcQpv22L;
 
webui_subscriptions_url = www.google.com
webui_subscriptions_button_text = Subscription
webui_subscriptions_invitation_text = You may also like to get a subscription

hostname=http://127.0.0.1:8088
dev.port=8088

apiPathZero=obp
token_expiration_weeks=400

jwt.public_key_rsa=src/main/resources/cert/private2.pem
allow_gateway_login= true
gateway.host=127.0.0.1

allow_dauth= true
dauth.host=127.0.0.1

## Set this to true if you want to allow users to create sandbox test accounts with a starting balance
allow_sandbox_account_creation=true

## Set this to true if you want to allow the "data import" api call
allow_sandbox_data_import=true

# Secret key that allows access to the "data import" api. You should change this to your own secret key
#obp-mapped (9.5-BigSql:5436)
sandbox_data_import_secret=77f5ae14-9723-486a-b083-a91ce921c9f8
## Set this to false if you don't want the api payments call to work (starting with v1.2.1)
payments_enabled=true

## Transaction requests are replacing simple payments starting from 1.4.0
transactionRequests_enabled=true
# The following is just used for TransactionRequestProvider, it is not connector, it is a long long ageo 
transactionRequests_connector=mapped

## Transaction Request Types that are supported on this server. Possible values might include SANDBOX_TAN, INTRABANK, SEPA, FREE_FORM
transactionRequests_supported_types=SANDBOX_TAN,SEPA,FREE_FORM,COUNTERPARTY,SIMPLE,CARD,ACCOUNT,AGENT_CASH_WITHDRAWAL,CARDANO,ETHEREUM,ETH_SEND_RAW_TRANSACTION,ETH_SEND_TRANSACTION,HOLD

# Ethereum RPC URL (default to local Anvil)
#ethereum.rpc.url=http://127.0.0.1:8545
# OBP chain
ethereum.rpc.url=https://nkotb.openbankproject.com

# # Ethereum RPC URL (default switched to private chain)
# ethereum.rpc.url=https://nkotb.openbankproject.com
# # Ethereum chain id for the private network
# ethereum.chain.id=2025
# # Default gas limit for simple ETH transfer (21000)
# ethereum.tx.gas=21000

answer_transactionRequest_challenge_allowed_attempts=1000

transactionRequests_challenge_threshold_TRANSFER_TO_PHONE=1000
transactionRequests_challenge_threshold_TRANSFER_TO_ACCOUNT=1000
transactionRequests_challenge_threshold_TRANSFER_TO_ATM=1000
transactionRequests_challenge_threshold_SEPA_CREDIT_TRANSFERS=1000
#transactionRequests_challenge_threshold_CARDANO=1000
#transactionRequests_challenge_threshold_ETHEREUM=1000
transactionRequests_challenge_threshold_HOLD=1000

## Gets current charge level for transaction request
## The Currency is EUR. Connector implementations may convert the value to the transaction request currency.
## Connector implementation may well provide dynamic response
transactionRequests_charge_level_SANDBOX_TAN=0.002
transactionRequests_charge_level_SEPA=0.002
transactionRequests_charge_level_COUNTERPARTY=0.002
transactionRequests_charge_level_FREE_FORM=0.002
#transactionRequests_charge_level_CARDANO=0.002
#transactionRequests_charge_level_ETHEREUM=0.002
#transactionRequests_charge_level_HOLD=0.002

## For video conference meetings (createMeeting)
meeting.tokbox_enabled=false
meeting.tokbox_api_key=changeme
meeting.tokbox_api_secret=changeme

### Management modules

## RabbitMQ settings (used to communicate with HBCI project)
connection.host=localhost
connection.user=theusername
connection.password=thepassword

## Secret key that allows access to the "add transactions" api. You should change this to your own secret key
importer_secret=gkzpqshdmfkcuutuooj4l0ozgqvq2nouikwdxk2d

## Set this to true if you want to have the api send a message to the hbci project to refresh transactions for an account
messageQueue.updateBankAccountsTransaction=false

## The minimum time between updates in hours
messageQueue.updateTransactionsInterval=1

## Set this to true if you want to have the api listen for "create account" messages from the hbci project
messageQueue.createBankAccounts=true

## Set this to true if you want to allow users to delete accounts (local ones like HBCI connected)
allow_account_deletion=true

## Secret key that allows access to api calls to get info about oauth tokens. You should change this
## to your own secret key
BankMockKey=change_me


## Web interface configuration
webui_header_logo_left_url = /media/images/logo.png
webui_header_logo_right_url =
webui_index_page_about_section_background_image_url = /media/images/about-background.jpg
webui_index_page_about_section_text = <p class="about-text"> \
                                        Welcome to the API Sandbox powered by the Open Bank Project! <br/> \
                                      </p>


# API Explorer url. Change to your instance
# webui_api_explorer_url = http://apiexplorer.openbankproject.com
webui_api_explorer_url = localhost:8082

# Sofi url. (AKA Social Finance) Change to your instance
# webui_sofi_url = http://sofi.openbankproject.com
webui_sofi_url = localhost:8081

# Starting page of documentation. Change this if you have a specific landing page.
webui_api_documentation_url = https://github.com/OpenBankProject/OBP-API/wiki


# To display a custom message above the username / password box
# We currently use this to display example customer login in sandbox etc.
webui_login_page_special_instructions=safsafasfsfaf

# Link for SDKs
webui_sdks_url = https://github.com/OpenBankProject/OBP-API/wiki/OAuth-Client-SDKS



## For partner logos and links
webui_main_partners=[\
{"logoUrl":"http://www.example.com/images/logo.png", "homePageUrl":"http://www.example.com", "altText":"Example 1"},\
{"logoUrl":"http://www.example.com/images/logo.png", "homePageUrl":"http://www.example.com", "altText":"Example 2"}]

# Main style sheet. Add your own if need be.
webui_main_style_sheet = /media/css/website.css

# Override certain elements (with important styles)
webui_override_style_sheet =

## Link to agree to Terms & Conditions, shown on signup page
webui_agree_terms_url =

## API Options
apiOptions.getBranchesIsPublic = true
apiOptions.getAtmsIsPublic = true
apiOptions.getProductsIsPublic = true™
apiOptions.getTransactionTypesIsPublic = true

## Default Bank. Incase the server wants to support a default bank so developers don't have to specify BANK_ID
## e.g. developers could use /my/accounts as well as /my/banks/BANK_ID/accounts
defaultBank.bank_id=gh.29.uk

# set localAdmin and susan.uk.29 
super_admin_user_ids=65356285-4e54-4559-ab8b-70ad8430e7f8,66214b8e-259e-44ad-8868-3eb47be70646,b1839f74-6f1a-4b31-bd76-595a83e17894,9b3778eb-7a5b-4586-b668-544a223ed2f0

display_accept_cookies_question=false
# When new consumers inserted they should use this setting.
consumers_enabled_by_default=true

# Set the limited bad login in attempt times,if the users try to login exceed it,  the user account should be locked
max.bad.login.attempts = 3000

# The Open redirect hostname white list
openredirects.hostname.whitlelist = http://localhost:8080,http://localhost:8081

# Autocomplete for login form has to be explicitly set
autocomplete_at_login_form_enabled=false

## Enable writing API metrics (which APIs are called) to RDBMS
write_metrics=true
write_connector_metrics=true

## ElasticSearch
allow_elasticsearch=false
allow_elasticsearch_warehouse=false
allow_elasticsearch_metrics=false
#es.cluster.name=elasticsearch

## ElasticSearch warehouse
es.warehouse.index=warehouse
#es.warehouse.host=localhost
es.warehouse.host=10.0.0.200
es.warehouse.port.tcp=9300
es.warehouse.port.http=9200
es.warehouse.allowed.indices=testone-channels_blocks,testone-customer_cards,testone-customer_transactions,testone-customer_details,testone-customer_accounts



remotedata.hostname=127.0.0.1
remotedata.port=2662
remotedata.secret=CHANGE_ME
remotedata.timeout=60

# Akka timeout configuration optimization
akka_connector.timeout=30
kafka.akka.timeout=30

# API endpoint timeout settings (milliseconds)
short_endpoint_timeout=5000
medium_endpoint_timeout=15000
long_endpoint_timeout=60000

# Database query timeout settings
database_query_timeout_in_seconds=30

# HikariCP connection pool timeout configuration
hikari.connectionTimeout=30000
hikari.idleTimeout=600000
hikari.maxLifetime=1800000

# Jetty HTTP server timeout configuration
jetty.idle.timeout=120000
jetty.request.timeout=120000
jetty.response.timeout=120000
remotedata.db.driver=org.h2.Driver
remotedata.db.url=jdbc:h2:./lift_proto.db.remotedata;DB_CLOSE_ON_EXIT=FALSE
remotedata.db.username=userInvalid signature
remotedata.db.password=secret

logging.database.queries.enable = true

use_consumer_limits = true

#sca_phone_api_key = ACxx5b72ab850501b580d8d4419db7xxxx
#sca_phone_api_secret = 7af7c2dac101d42769dff87a22a6eb96
#sca_phone_api_id = MGa1698309f110d0a1da7e698876ca1004

documented_server_url = http://localhost:8080

webui_create_consumer_successful_message =  Thank you for registering to use the TAB Bank API.

#app_mode=portal
webui_agree_privacy_policy_url = https://openbankproject.com/privacy-policy
#webui_agree_privacy_policy_html_text = 123123

webui_show_dummy_user_tokens=true
#resource_docs_requires_role=true
authUser.skipEmailValidation=true

ACCOUNT_OTP_INSTRUCTION_TRANSPORT=dummy
SIMPLE_OTP_INSTRUCTION_TRANSPORT=dummy
HOLD_OTP_INSTRUCTION_TRANSPORT=dummy
ACCOUNT_OTP_INSTRUCTION_TRANSPORT=dummy
SANDBOX_TAN_OTP_INSTRUCTION_TRANSPORT=dummy
SEPA_OTP_INSTRUCTION_TRANSPORT=dummy
FREE_FORM_OTP_INSTRUCTION_TRANSPORT=dummy
COUNTERPARTY_OTP_INSTRUCTION_TRANSPORT=dummy
CARD_OTP_INSTRUCTION_TRANSPORT=dummy
SEPA_CREDIT_TRANSFERS_OTP_INSTRUCTION_TRANSPORT=dummy
AGENT_CASH_WITHDRAWAL_OTP_INSTRUCTION_TRANSPORT=dummy

apiOptions.getProductsIsPublic=true
webui_main_faq_external_link=https://static.openbankproject.com/nmb/mainfaq.html

allow_user_generated_scala_code=false

can_grant_access_to_views=["",""]
can_revoke_access_to_views=["",""]

#webui_user_invitation_notice_text=Thank you for expressing interest in the API Playground. At this time access to the \
                                    API Playground is on an invitation basis only. Those invited will be invited to join \
                                    by email, where you will be able to complete registration.123131313
                                    
                                    
cache.redis.url=127.0.0.1
cache.redis.port=6379


session_inactivity_timeout_in_minutes=10080



entitlement_list_1=CanCreateBank
new_user_entitlement_list=entitlement_list_1

mirror_request_headers_to_response=DirectLogin
user_account_validated=true       


#connector.cache.ttl.seconds=0
#connector.cache.ttl.seconds.getBank=0
#connector.cache.ttl.seconds.getBanks=0
#connector.cache.ttl.seconds.getUser=0
#connector.cache.ttl.seconds.getAccount=0
#connector.cache.ttl.seconds.getAccounts=0
#connector.cache.ttl.seconds.getTransaction=0
#connector.cache.ttl.seconds.getTransactions=0
#connector.cache.ttl.seconds.getTransactionRequests210=0
#connector.cache.ttl.seconds.getCounterparties=0
#connector.cache.ttl.seconds.getCounterpartyByCounterpartyId=0
#connector.cache.ttl.seconds.getCounterpartyTrait=0
#connector.cache.ttl.seconds.getCustomersByUserId=0
#connector.cache.ttl.seconds.getBranches=0
#connector.cache.ttl.seconds.getBranch=0
#connector.cache.ttl.seconds.getAtms=0
#connector.cache.ttl.seconds.getAtm=0
#connector.cache.ttl.seconds.getBankAccountsBalances=0
#connector.cache.ttl.seconds.getCounterpartyFromTransaction=0
#connector.cache.ttl.seconds.getCounterpartiesFromTransaction=0
#connector.cache.ttl.seconds.APIMethods121.getStatusOfCreditCardOrderFuture=0
#connector.cache.ttl.seconds.APIMethods121.getStatusOfCheckbookOrdersFuture=0
#MapperCounterparties.cache.ttl.seconds.getOrCreateMetadata=0
#api.cache.ttl.seconds.APIMethods121.getTransactions=0            
#methodRouting.cache.ttl.seconds=0
#endpointMapping.cache.ttl.seconds=0
webui.props.cache.ttl.seconds=1000
dynamicEntity.cache.ttl.seconds=0
dynamicEndpoint.cache.ttl.seconds=0
#validation.cache.ttl.seconds=0
#authTypeValidation.cache.ttl.seconds=0
#connectorMethod.cache.ttl.seconds=0
#transactionRequest.challenge.ttl.seconds=0
#userAuthContextUpdateRequest.challenge.ttl.seconds=0
#user_invitation.ttl.seconds=0

dynamicResourceDocsObp.cache.ttl.seconds=0
staticResourceDocsObp.cache.ttl.seconds=0
createLocalisedResourceDocJson.cache.ttl.seconds=0


#user_invitation.mandatory=true
cache.redis.port=6379
show_used_connector_methods=true

#api_enabled_versions=[OBPv5.1.0]
#api_enabled_endpoints=[OBPv5.1.0-root]
#MappedMetrics.cache.ttl.seconds.getTopApis=0



enable_metrics_scheduler = true
retain_archive_metrics_days = 1095
retain_metrics_days = 15
retain_metrics_move_limit = 50000
retain_metrics_scheduler_interval_in_seconds = 3600
MappedMetrics.cache.ttl.seconds.getAllMetrics=0
consents.max_time_to_live=3600000


#9fcf8ccd-0c8a-4b3e-8725-73c41b2d9bed --> API_Explorer_II
# Grantor = the frontend consumer creating the consent; Grantee = Opey-II (76dacc33).
# Both the consumer_key and the internal consumer_id are listed per app, because the
# match value differs by setup (Portal historically uses its key as the id).
#   Portal           : key 939fa68d… / id 6efe6f62…
#   API-Explorer-II  : key c9b0ddce… / id ac2f33a2…
#   API-Manager-II   : key be6c8c6d… / id 6cd28ce0…
#   Opey_II (grantee): 76dacc33…
skip_consent_sca_for_consumer_id_pairs=[{ \
    "grantor_consumer_id": "939fa68d-5840-4e2d-abcd-d1b14e3d7ca8",\
    "grantee_consumer_id": "76dacc33-3990-4de4-9e02-876829627ebe" \
},{ \
    "grantor_consumer_id": "6efe6f62-bbd7-482b-b50a-1af6bfa47898",\
    "grantee_consumer_id": "76dacc33-3990-4de4-9e02-876829627ebe" \
},{ \
    "grantor_consumer_id": "c9b0ddce-ceb8-4c11-8536-5af926d950fb",\
    "grantee_consumer_id": "76dacc33-3990-4de4-9e02-876829627ebe" \
},{ \
    "grantor_consumer_id": "ac2f33a2-71ad-4ef0-b093-e9ae2487bfe5",\
    "grantee_consumer_id": "76dacc33-3990-4de4-9e02-876829627ebe" \
},{ \
    "grantor_consumer_id": "be6c8c6d-6dbc-474d-b1fb-7db550cd244c",\
    "grantee_consumer_id": "76dacc33-3990-4de4-9e02-876829627ebe" \
},{ \
    "grantor_consumer_id": "6cd28ce0-ecde-4fed-93f8-44af9309a9c3",\
    "grantee_consumer_id": "76dacc33-3990-4de4-9e02-876829627ebe" \
}]

#session_inactivity_timeout_in_seconds = 3000000

#super_admin_username = TomW illiams
#super_admin_inital_password = 12313 
#super_admin_email = tom@tesobe.com

# -- Keycloak OAuth 2 ---------------------------------------------------------------------------
integrate_with_keycloak = true
# Keycloak Identity Provider Host
# oauth2.keycloak.host=http://localhost:7070
# Keycloak access token to make a call to Admin APIs (This props is likely to change)
# keycloak.admin.access_token =
# Keycloak Identity Provider Realm (Multi-Tenancy Support)
# oauth2.keycloak.realm = master
# oauth2.keycloak.well_known=http://localhost:7070/realms/master/.well-known/openid-configuration
# Used to sync IAM of OBP-API and IAM of Keycloak
oauth2.keycloak.source_of_truth = true
# Resource access object allowed to sync IAM of OBP-API and IAM of Keycloak
oauth2.keycloak.resource_access_key_name_to_trust = open-bank-project
# Keycloak (local) runtime endpoints
oauth2.keycloak.host=http://localhost:8000/realms/master
oauth2.keycloak.well_known=http://localhost:8000/realms/master/.well-known/openid-configuration
# ------------------------------------------------------------------------ Keycloak OAuth 2 ------


openid_connect.enabled=true
## Google
<!-- openid_connect_1.client_secret=9R96jSaXkO2vjnNOS815-b-- -->
<!-- openid_connect_1.client_id=177358456100-046n99ooqrasvl83nt3mu3u4cna1db5o.apps.googleusercontent.com  -->
<!-- openid_connect_1.callback_url=https://test.openbankproject.com/auth/openid-connect/callback -->
<!-- openid_connect_1.endpoint.authorization=https://accounts.google.com/o/oauth2/v2/auth -->
<!-- openid_connect_1.endpoint.userinfo=https://openidconnect.googleapis.com/v1/userinfo -->
<!-- openid_connect_1.endpoint.token=https://oauth2.googleapis.com/token  -->
<!-- openid_connect_1.endpoint.jwks_uri=https://www.googleapis.com/oauth2/v3/certs -->
<!-- openid_connect_1.access_type_offline=true -->
<!-- openid_connect_1.callback_url=https://test.openbankproject.com/auth/openid-connect/callback -->
<!-- openid_connect_1.button_text = Google -->

## Keycloak
openid_connect.scope=openid email profile   
    
openid_connect_2.client_secret=Pd8yBSqFSKtuDmGg3wm23CpSMilmuN2H
openid_connect_2.client_id=ae8e657f-4c2f-4eda-afe4-8140930ce4aa
openid_connect_2.callback_url=https://test.openbankproject.com/auth/openid-connect/callback-2
openid_connect_2.endpoint.authorization=https://test-oauth2.openbankproject.com/realms/obp-test/protocol/openid-connect/auth
openid_connect_2.endpoint.userinfo=https://test-oauth2.openbankproject.com/realms/obp-test/protocol/openid-connect/userinfo
openid_connect_2.endpoint.token=https://test-oauth2.openbankproject.com/realms/obp-test/protocol/openid-connect/token
openid_connect_2.endpoint.jwks_uri=https://test-oauth2.openbankproject.com/realms/obp-test/protocol/openid-connect/certs
openid_connect_2.access_type_offline=true
openid_connect_2.button_text = Keycloak




# ------------------------------------------------------------------------ OBP-OIDC (Local) ----
openid_connect_1.client_secret=eEW7ImTFV1jiFwCSSHs7cLeFZPGUbMkPfNE25pJW7I4
openid_connect_1.client_id=31fba5ca-9adb-4c05-b784-6993153f5dd2
openid_connect_1.callback_url=http://localhost:8080/auth/openid-connect/callback
openid_connect_1.endpoint.authorization=http://localhost:9000/obp-oidc/auth
openid_connect_1.endpoint.userinfo=http://localhost:9000/obp-oidc/userinfo
openid_connect_1.endpoint.token=http://localhost:9000/obp-oidc/token
openid_connect_1.endpoint.jwks_uri=http://localhost:9000/obp-oidc/jwks
openid_connect_1.access_type_offline=true
openid_connect_1.button_text = OBP OpenID Connect
# ------------------------------------------------------------------------ OBP-OIDC (Local) ----

# Expose OBP-OIDC and Keycloak in OBP-API well-known providers
oauth2.oidc_provider=obp-oidc,keycloak
# Well-known \\
scovery URL for OBP-OIDC (explicit)
oauth2.obp_oidc.host=http://localhost:9000
oauth2.obp_oidc.well_known=http://localhost:9000/obp-oidc/.well-known/openid-configuration

# Ensure issuer and JWKS URL match the OBP-OIDC server
oauth2.obp_oidc.issuer=http://localhost:9000/obp-oidc
oauth2.jwk_set.url=http://localhost:8000/realms/master/protocol/openid-connect/certs,http://localhost:9000/obp-oidc/jwks


psu_authentication_method = redirection
psu_authentication_method_sca_redirect_url = http://127.0.0.1:8080/confirdm-bg-consent-request?CONSENT_ID=PLACEHOLDER
consents.sca.enabled=false


berlin_group_frequency_per_day_upper_limit=1000
dynamic_code_sandbox_permissions=[\
    new java.net.NetPermission("specifyStreamHandler"),\
    new java.lang.reflect.ReflectPermission("suppressAccessChecks"),\
    new java.lang.RuntimePermission("getenv.*"),\
    new java.util.PropertyPermission("cglib.useCache", "read"),\
    new java.util.PropertyPermission("net.sf.cglib.test.stressHashCodes", "read"),\
    new java.util.PropertyPermission("cglib.debugLocation", "read"),\
    new java.lang.RuntimePermission("accessDeclaredMembers"),\
    new java.lang.RuntimePermission("getClassLoader")\
]

dynamicResourceDoc.cache.ttl.seconds=50


berlin_group_mandatory_headers = 
berlin_group_mandatory_header_consent = 
transactionRequests_payment_limit=10000000000000
# Email Configuration for Testing
#mail.api.consumer.registered.notification.send=true
#mail.api.consumer.registered.sender.address=test@localhost
#mail.api.consumer.registered.notification.addresses=test@localhost
#mail.smtp.host=localhost
#mail.smtp.port=1025
#mail.smtp.auth=false
#mail.exception.sender.address=test@localhost
#mail.exception.registered.notification.addresses=test@localhost
#mail.debug=true
#mail.users.userinfo.sender.address=test@localhost

# Email Configuration for Production Testing
mail.api.consumer.registered.notification.send=true
mail.api.consumer.registered.sender.address=hongwei@tesobe.com
mail.api.consumer.registered.notification.addresses=hongwei@tesobe.com

# SMTP Configuration for Tesobe Mail Server
#mail.smtp.host=mail.tesobe.com
#mail.smtp.port=25
#mail.smtp.auth=true
#mail.smtp.user=hongwei@tesobe.com
#mail.smtp.password=WEI520lu
#mail.smtp.starttls.enable=true
#mail.smtp.ssl.enable=true
#mail.smtp.ssl.protocols=TLSv1.2

# Exception and Notification Addresses
mail.exception.sender.address=hongwei@tesobe.com
mail.exception.registered.notification.addresses=hongwei@tesobe.com
mail.users.userinfo.sender.address=hongwei@tesobe.com

# Debug Settings
mail.debug=true
#berlin_group_v1_3_alias_path=1231323
experimental_become_user_that_created_consent=true

# ── App Directory URLs (shown on localhost:8080 discovery page) ──────────────
public_obp_api_url=http://localhost:8080
public_obp_portal_url=http://localhost:5174
public_obp_api_explorer_url=http://localhost:5173
public_obp_api_manager_url=http://localhost:3003
public_obp_oidc_url=http://localhost:9000
public_obp_opey_url=http://localhost:5000


dynamic_entity.indexing.backend=auto