// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package code.bankconnectors.grpc.api

object ApiProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.empty.EmptyProto,
    com.google.protobuf.timestamp.TimestampProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      code.bankconnectors.grpc.api.BankIdGrpc,
      code.bankconnectors.grpc.api.BankRoutingJsonV121Grpc,
      code.bankconnectors.grpc.api.BankJson400Grpc,
      code.bankconnectors.grpc.api.BanksJson400Grpc
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CglhcGkucHJvdG8SGGNvZGUuYmFua2Nvbm5lY3RvcnMuZ3JwYxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGh9nb29nb
  GUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvIiUKCkJhbmtJZEdycGMSFwoCaWQYASABKAlCB+I/BBICaWRSAmlkImYKF0JhbmtSb
  3V0aW5nSnNvblYxMjFHcnBjEiMKBnNjaGVtZRgBIAEoCUIL4j8IEgZzY2hlbWVSBnNjaGVtZRImCgdhZGRyZXNzGAIgASgJQgziP
  wkSB2FkZHJlc3NSB2FkZHJlc3MitwIKD0JhbmtKc29uNDAwR3JwYxIXCgJpZBgBIAEoCUIH4j8EEgJpZFICaWQSLQoKc2hvcnRfb
  mFtZRgCIAEoCUIO4j8LEglzaG9ydE5hbWVSCXNob3J0TmFtZRIqCglmdWxsX25hbWUYAyABKAlCDeI/ChIIZnVsbE5hbWVSCGZ1b
  GxOYW1lEh0KBGxvZ28YBCABKAlCCeI/BhIEbG9nb1IEbG9nbxImCgd3ZWJzaXRlGAUgASgJQgziPwkSB3dlYnNpdGVSB3dlYnNpd
  GUSaQoNYmFua19yb3V0aW5ncxgGIAMoCzIxLmNvZGUuYmFua2Nvbm5lY3RvcnMuZ3JwYy5CYW5rUm91dGluZ0pzb25WMTIxR3JwY
  0IR4j8OEgxiYW5rUm91dGluZ3NSDGJhbmtSb3V0aW5ncyJfChBCYW5rc0pzb240MDBHcnBjEksKBWJhbmtzGAEgAygLMikuY29kZ
  S5iYW5rY29ubmVjdG9ycy5ncnBjLkJhbmtKc29uNDAwR3JwY0IK4j8HEgViYW5rc1IFYmFua3MyvAEKCk9icFNlcnZpY2USUAoIZ
  2V0QmFua3MSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaKi5jb2RlLmJhbmtjb25uZWN0b3JzLmdycGMuQmFua3NKc29uNDAwR3JwY
  yIAElwKB2dldEJhbmsSJC5jb2RlLmJhbmtjb25uZWN0b3JzLmdycGMuQmFua0lkR3JwYxopLmNvZGUuYmFua2Nvbm5lY3RvcnMuZ
  3JwYy5CYW5rSnNvbjQwMEdycGMiAGIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      com.google.protobuf.empty.EmptyProto.javaDescriptor,
      com.google.protobuf.timestamp.TimestampProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}